// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htgggbmcurvlscyyfzoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0Z2dnYm1jdXJ2bHNjeXlmem9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MTgyNjQsImV4cCI6MjA5MzM5NDI2NH0.Mbg-A_a39legzmWJbCcwn6Ut2omGcqhEDvJvamghDRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});